-- liquibase formatted sql

-- changeset Kris:2


create table zone
(
    added_at timestamp,
    id       bigint generated by default as identity
        primary key,
    name     varchar(255),
    address  varchar(255)
);

alter table zone
    owner to kris;