-- liquibase formatted sql

-- changeset Kris:1


create table pass
(
    added_at timestamp,
    id       bigint generated by default as identity
        primary key,
    name     varchar(255),
    surname  varchar(255),
    updated_at timestamp,
    begin_time timestamp,
    end_time timestamp,
    status varchar(255)

);

alter table pass
    owner to kris;